import { createClient } from "@supabase/supabase-js";
import {Cloudinary} from "@cloudinary/url-gen"

export const seattle = { lat: 47.6262, lng: -122.3321 };

export const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);

export const GMKey = import.meta.env.VITE_GOOGLE_MAPS_KEY;

export const cld = new Cloudinary({
  cloud: {
    cloudName: import.meta.env.VITE_CDN_LIBRARY_NAME
  }
}) 

export const neighborhoods = [
    "Alki",
    "Arbor Heights",
    "Atlantic",
    "Ballard",
    "Belltown",
    "Bitter Lake",
    "Blue Ridge",
    "Briarcliff",
    "Brighton",
    "Broadview",
    "Bryant",
    "Capitol Hill",
    "Capitol Hill - Broadway",
    "Cedar Park",
    "Central Business District",
    "Central District",
    "Columbia City",
    "Crown Hill",
    "Denny Triangle",
    "Downtown Seattle",
    "Dunlap",
    "Eastlake",
    "East Queen Anne",
    "Fairmount Park",
    "Fauntelroy",
    "First Hill",
    "Fremont",
    "Gatewood",
    "Genesee",
    "Georgetown",
    "Green Lake",
    "Greenwood",
    "Haller Lake",
    "Harbor Island",
    "Harrison / Denny-Blaine",
    "High Point",
    "Highland Park",
    "Holly Park",
    "Industrial District",
    "Interbay",
    "International District",
    "Judkins Park",
    "Lake City",
    "Laurelhurst",
    "Lawton Park",
    "Leschi",
    "Licton Springs",
    "Lower Queen Anne",
    "Loyal Heights",
    "Madison Park",
    "Madrona",
    "Magnolia",
    "Maple Leaf",
    "Matthews Beach",
    "Meadowbrook",
    "Mid-Beacon Hill",
    "Minor",
    "Montlake",
    "Mount Baker",
    "North Admiral",
    "North Beacon Hill",
    "North Delridge",
    "North Queen Anne",
    "Northgate",
    "Olympic Hills",
    "Portage Bay",
    "Phinney Ridge",
    "Pinehurst",
    "Pioneer Square",
    "Rainier Beach",
    "Rainier View",
    "Ravenna",
    "Riverview",
    "Roxhill",
    "Sand Point",
    "Seaview",
    "Seward Park",
    "SoDo",
    "South Beacon Hill",
    "South Delridge",
    "Southeast Magnolia",
    "South Lake Union",
    "South Park",
    "Stevens",
    "Sunset Hill",
    "University District",
    "University Heights",
    "University of Washington",
    "Victory Heights",
    "View Ridge",
    "Wallingford",
    "Wedgwood",
    "Westlake",
    "Windermere",
    "West Queen Anne",
    "West Woodland",
    "Whittier Heights",
    "Yesler Terrace"
  ];
