export const seattle = { lat: 47.6262, lng: -122.3321 };

export const neighborhoods = [
    "Alki",
    "Ballard",
    "Bitter Lake",
    "Broadview",
    "Capitol Hill",
    "Capitol Hill - Broadway",
    "Cedar Park",
    "Central District",
    "Columbia City",
    "Crown Hill",
    "Downtown Seattle",
    "Dunlap",
    "Fauntelroy",
    "First Hill",
    "Fremont",
    "Genesee",
    "Georgetown",
    "Green Lake",
    "Greenwood",
    "Haller Lake",
    "High Point",
    "Highland Park",
    "Holly Park",
    "Industrial District",
    "Interbay",
    "International District",
    "Judkins Park",
    "Lake City",
    "Laurelhurst",
    "Licton Springs",
    "Lower Queen Anne",
    "Loyal Heights",
    "Madison Park",
    "Madrona",
    "Magnolia",
    "Maple Leaf",
    "Matthews Beach",
    "Meadowbrook",
    "Mid-Beacon Hill",
    "Montlake",
    "Mount Baker",
    "North Admiral",
    "North Beacon Hill",
    "North Delridge",
    "Northgate",
    "Olympic Hills",
    "Phinney Ridge",
    "Pinehurst",
    "Pioneer Square",
    "Queen Anne",
    "Rainier Beach",
    "Ravenna",
    "Sand Point",
    "Seward Park",
    "SoDo",
    "South Beacon Hill",
    "South Lake Union",
    "South Park",
    "Stevens",
    "Sunset Hill",
    "University District",
    "University Heights",
    "View Ridge",
    "Wallingford",
    "Wedgwood",
    "West Queen Anne",
    "West Woodland",
  ];
